version: "3.8"

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./nextjs-app
          target: /src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
